name: build

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  Build:
    name: application build and deploy
    runs-on: ubuntu-latest

    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@master

      # install nodejs
      - uses: actions/setup-node@master
        with:
          node-version: 12.x

      # install libraries and build
      - name: install and build
        run: |
          yarn install
          yarn build

  Deploy:
    needs:
      - Build

    name: terraform build and apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
  
      - name: Terraform Plan and Apply
        working-directory: terraform
        run: |
          curl -O https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
          unzip terraform_0.13.5_linux_amd64.zip
          terraform init
          terraform plan -no-color
          terraform apply -auto-approve
        env:
          TF_VAR_sfdc_access_token: ${{ secrets.SFDC_ACCESS_TOKEN }}
          TF_VAR_sfdc_consumer_key: ${{ secrets.SFDC_CONSUMER_KEY }}
          TF_VAR_sfdc_consumer_secret: ${{ secrets.SFDC_CONSUMER_SECRET }}
          TF_VAR_sfdc_username: ${{ secrets.SFDC_USERNAME }}
          TF_VAR_sfdc_password: ${{ secrets.SFDC_PASSWORD }}

