name: build

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-northeast-1

jobs:
  Build:
    name: amazon-connect-bootcamp
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
  
      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan and Apply
        working-directory: terraform
        run: |
          terraform plan -no-color
          terraform apply -auto-approve
        env:
          TF_VAR_sfdc_consumer_key: ${{ secrets.SFDC_CONSUMER_KEY }}
          TF_VAR_sfdc_consumer_secret: ${{ secrets.SFDC_CONSUMER_SECRET }}
          TF_VAR_sfdc_access_token: ${{ secrets.SFDC_ACCESS_TOKEN }}
          TF_VAR_sfdc_username: ${{ secrets.SFDC_USERNAME }}
          TF_VAR_sfdc_password: ${{ secrets.SFDC_PASSWORD }}
